//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFilmProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film_Nomineringer
    {
        public int Film_ID { get; set; }
        public string Titel { get; set; }
        public string Instruktør { get; set; }
        public string Genre { get; set; }
        public Nullable<System.DateTime> Årstal { get; set; }
        public string Image { get; set; }
    }
}
